apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: meda
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dockerdep-10-app
        image: ethen.azurecr.io/dotnet-demoapp:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      -name: nithin